### ISSUE TITLE
getmac returns None Mac address in homeassistant environment

### ISSUE THREAD

**Issue by mark007** [GhostofGoes/getmac#83]
**Describe the bug**
Hi. Various integrations within the homeassistant GitHub project seem to be having issues in its most recent versions, where integrations that use getmac to get the Mac address, are returning None. Forcing the method seems to work as a workaround but it feels wrong to have to force the method.

https://github.com/home-assistant/core/issues/87623

https://github.com/home-assistant/core/issues/87146

**To Reproduce**
Install the latest 2023.x.x versions of homeassistant and any integration using the getmac library like the kef integration. See how calls to get Mac with the default method, return none but when forcing the method to ArpFile, the Mac is returned.

**Expected behavior**
I would have expected the default mode to have worked like it did in older 2022.x.x versions of home assistant. It's unclear to me what change in homeassistant has affected getmac such as python 3.9 Vs 3.10 or something else.

**System info**
(please complete the following information):
 - OS name (e.g. Windows 10 x64): haos (home assistant os) x64.
 - OS Version (e.g. 1804 build 17134): Based on buildroot 2022.02.9
 - Python version (e.g. CPython 3.6.5 x64): 3.10
 - getmac version (e.g. getmac 0.8.3): 0.8.2 but tried 0.9.2 also

**Additional context**

**Comment by GhostofGoes** [comment]
If I'm understanding correctly, this is happening with both getmac 0.8.2 and 0.9.2?

Is there a way I can reproduce the bug on my system in order to test fix(s)? I haven't used homeassistant before, though I'm familiar with the project (been meaning to set it up in my home, just haven't had the time haha).

Based on my initial look last night at the two issues you originally linked, there may be more than one problem at play here. Being able to debug locally would help me isolate exactly what's happening and hopefully get a fix in soon.

**Comment by mark007** [comment]
I'll try to find the most minimal way to reproduce it. I'll see if spinning up a homeassistant container and not going through the full setup process, allows me to then install getmac on a second shell in the container and test from there..

**Comment by mark007** [comment]
OK, on my unraid server, I fired up a docker image of homeassistant. I had to run it in --net=host mode to get any sort of response but this sample test.py file along with this docker command, shows the first command returns None where as the second call returns the mac address for my particular IP. In a pure python3.9 or pure python3.10 docker image from dockerhub, both work fine.

```
import getmac
from getmac import get_mac_address

print(get_mac_address(ip="192.168.8.162"))

getmac.getmac.FORCE_METHOD="ArpFile"
print(get_mac_address(ip="192.168.8.162"))
```

And the docker image call.

`docker run --net=host -v $PWD:$PWD --entrypoint python homeassistant/home-assistant $PWD/test.py`

Output on my ;machine is below, somewhat redacted.

```
None
84:17:15:xx:xx:xx
```

**Comment by GhostofGoes** [comment]
Thank you for the detailed information, I'll take a look tonight when I get home from work.

It's likely due to a change in Python's UUID module that occurred in recent versions of CPython, I'll have to dig deeper tonight to be sure though.


> Trying to see whats different between the two, the pip list shows a different, surprising to me theres a getmac and a get-mac.
> 

Yes, they're the same package 😅 . A long time ago, I originally published the package as `get-mac`, and later changed it to `getmac` (this was back in 2017 or 2018 IIRC). Many people still had `get-mac` in their dependencies so I just kept publishing updates to both packages for the sake of compatibility, and to ensure people still got updates and fixes. At some point (maybe 1.0.0) I'll stop updating `get-mac`.

**Comment by mark007** [comment]
Cheers. To my eyes it seems because both packages contain the same python directory inside titled 'getmac' that installing both packages will always result in only one of the packages alphabetically (I guess get-mac) getting used. If this is the case I guess you could guide us as to the best solution.

**Comment by mark007** [comment]
I wonder if get-mac was uplifted for now to match getmac, we could then try to move packages in the homeassistant project, away from the get-mac version.

Running a pipdepree within the latest homeassistant docker image, shows this is the package that's still using get-mac, asking for any version.

vilfo-api-client==0.3.2                            
  - get-mac [required: Any, installed: 0.9.1]

If a 0.9.2 of it was also released to match getmac, it might be a temporary fix?

**Comment by GhostofGoes** [comment]
Ha, I never actually published 0.9.2 for `get-mac`. I'll try that now, and investigate some more this weekend.

**Comment by GhostofGoes** [comment]
Alright, `get-mac` is updated to 0.9.2. homeassistant dependencies really should be updated to use `getmac` in requirements.txt, and remove any references to `get-mac`.

**Comment by mark007** [comment]
Thanks @GhostofGoes I will try to remove references in the homeassistant core repo, thanks for the update, I'll close this one.

**Comment by GhostofGoes** [comment]
Let's leave this open, since forcing the ArpFile method is something I'd like to address with a proper fix. 

There's [some special logic in getmac regarding lookup of MACs from IPv4 addresses](https://github.com/GhostofGoes/getmac/blob/558facf3b2fc031261a1350533328eb7150d42c9/getmac/getmac.py#L1758) that I'd like to improve. What should happen is getmac should check the ARP table first using the `ArpFile` method (if it's on a Linux system and the file exists), and if the IP isn't in the ARP table, then fall back to the normal way of doing things (use `arping` if it's available, otherwise send a UDP packet then check the ARP table). 

Additionally, I'd like to add an explicit check for busybox to handle it's variant of `arping`. From glancing at the documentation, it doesn't appear to do what we want (get a MAC from a IP), so what I'll likely do is add a check for busybox, which if true will mark the `ArpingHost` method as unusable

There's a lot going on in personal life right now so fix may take a bit, tentatively planning on having it done by Sunday, we'll see how it goes 😅

**Comment by GhostofGoes** [comment]
@mark007 0.9.4 release addresses several issues that may fix this for good. I've added support for BusyBox's `arping`, so that should work as a fallback if `ArpFile` fails. And if `ArpFile` works, then it'll just be used and `arping` won't be touched, noticeably improving performance (spawning a process takes orders of magnitude longer than reading a file).

**Comment by dixi83** [comment]
I was having this issue as well in a home assistant container. adding the `network_request=True` property solved the issue for me. Hope it helps someone who hits this issue.
